steps:
  # Build the client image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mcp-client:$BUILD_ID'
      - './mcp_client'

  # Push the client image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mcp-client:$BUILD_ID'

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'mcp-client'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mcp-client:$BUILD_ID'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--set-env-vars'
      - 'MCP_SERVER_URL=https://mcp-server-XXXXXXXXXX-ew.a.run.app'

images:
  - 'gcr.io/$PROJECT_ID/mcp-client:$BUILD_ID'